//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delsoft.Calendars.Belgian.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Delsoft.Agendas.Belgian.Resources.Translation", typeof(Translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armistice.
        /// </summary>
        internal static string Armistice {
            get {
                return ResourceManager.GetString("Armistice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascent.
        /// </summary>
        internal static string Ascent {
            get {
                return ResourceManager.GetString("Ascent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assumption.
        /// </summary>
        internal static string Assumption {
            get {
                return ResourceManager.GetString("Assumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christmas.
        /// </summary>
        internal static string Christmas {
            get {
                return ResourceManager.GetString("Christmas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easter.
        /// </summary>
        internal static string Easter {
            get {
                return ResourceManager.GetString("Easter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easter Monday.
        /// </summary>
        internal static string EasterMonday {
            get {
                return ResourceManager.GetString("EasterMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labor Day.
        /// </summary>
        internal static string LaborDay {
            get {
                return ResourceManager.GetString("LaborDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Holiday.
        /// </summary>
        internal static string NationalHoliday {
            get {
                return ResourceManager.GetString("NationalHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Year.
        /// </summary>
        internal static string NewYear {
            get {
                return ResourceManager.GetString("NewYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pentecost Monday.
        /// </summary>
        internal static string PentecostMonday {
            get {
                return ResourceManager.GetString("PentecostMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toussaint.
        /// </summary>
        internal static string Toussaint {
            get {
                return ResourceManager.GetString("Toussaint", resourceCulture);
            }
        }
    }
}
