name: Build, Pack and Publish

on: 
  push:
    branches:
      - release/*
      
jobs:
  prerelease:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal
    - name: Pack
      run: dotnet pack Delsoft.Calendars.sln -c Release --no-build --verbosity normal --version-suffix beta
    - name: Publish
      run: dotnet nuget push */bin/Release/*.nupkg -s https://nuget.pkg.github.com/diplomegalo/index.json -k ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
